# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_feed_itemable}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Amir Manji", "Russ Smith (russ@bashme.org)"]
  s.date = %q{2010-11-10}
  s.description = %q{Feed items for a Facebook like wall.}
  s.email = %q{https://github.com/amirmanji/acts_as_feed_itemable}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "generators/feed_item/feed_item_generator.rb",
     "generators/feed_item/templates/create_feed_items.rb",
     "generators/feed_item/templates/feed_item.rb",
     "init.rb",
     "lib/acts_as_feed_itemable.rb",
     "shoulda_macros/acts_as_feed_itemable.rb",
     "test/acts_as_feed_itemable_test.rb",
     "test/models.rb",
     "test/schema.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{https://github.com/amirmanji/acts_as_feed_itemable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Feed items for a Facebook like wall.}
  s.test_files = [
    "test/acts_as_feed_itemable_test.rb",
     "test/models.rb",
     "test/schema.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 1.3.0"])
    else
      s.add_dependency(%q<rspec>, ["~> 1.3.0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 1.3.0"])
  end
end

